"""Estimate [length, tolerance] bone constraints for optimization.bodypart_distance(_weak) from our own data.

Reads raw triangulations (points_3d*/original.h5) of any number of sessions, pooled regardless of cage,
and prints a YAML block to paste into the config. Which pairs are constrained, and whether they are
strong or weak, is taken from the config itself; only the values are re-estimated.

For each bone: per-session median over clean frames (head, ears, neck, spinemid and tailbase all
triangulated), then length = midpoint of the session medians and tolerance = half their range plus a
margin, so every session's typical length falls inside the unpenalized band.

Example (from tools/):
    python estimate_bone_lengths.py /scratch/VideoTracking/Videos/2607[2-3]*/*/Output/points_3d* \
        /scratch/VideoTracking/Videos/2608[01]*/*/Output/points_3d*
"""
import argparse
import logging
from pathlib import Path

import h5py
import numpy as np
import yaml

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(name)s - %(message)s')
logger = logging.getLogger(__name__)

CLEAN_FRAME_BODYPARTS = ['head', 'leftear', 'rightear', 'neck', 'spinemid', 'tailbase']

parser = argparse.ArgumentParser()
parser.add_argument("points_3d_dirs", nargs='+', help="points_3d directories containing original.h5")
parser.add_argument("-c", "--config", default='../configs/default.yaml', help="Config whose constrained pairs are re-estimated")
parser.add_argument("-m", "--margin", type=float, default=0.05, help="Tolerance margin, as a fraction of the length (default 0.05)")
parser.add_argument("--min-frames", type=int, default=1000, help="Skip sessions with fewer clean frames (default 1000)")
args = parser.parse_args()

with open(args.config) as f:
    config = yaml.safe_load(f)
bodyparts = config['animal']['bodyparts']
bodypart_indices = {bp: i for i, bp in enumerate(bodyparts)}
sections = {key: list(config['optimization'][key]) for key in ['bodypart_distance', 'bodypart_distance_weak']}
bones = [bone for pairs in sections.values() for bone in pairs]
clean_indices = [bodypart_indices[bp] for bp in CLEAN_FRAME_BODYPARTS]

session_medians = {bone: [] for bone in bones}
for points_3d_dir in args.points_3d_dirs:
    points_3d_path = Path(points_3d_dir) / 'original.h5'
    if not points_3d_path.is_file():
        logger.warning(f'Skipping {points_3d_dir}: no original.h5')
        continue
    with h5py.File(points_3d_path, 'r') as f:
        tracks = [np.array(f[name])[..., :3] for name in f]

    for points_3d in tracks:
        clean = ~np.isnan(points_3d[:, clean_indices, 0]).any(axis=1)
        if clean.sum() < args.min_frames:
            logger.warning(f'Skipping a track of {points_3d_dir}: only {clean.sum()} clean frames')
            continue
        for bone in bones:
            bp1, bp2 = [bodypart_indices[bp.strip()] for bp in bone.split('-')]
            lengths = np.linalg.norm(points_3d[clean, bp1] - points_3d[clean, bp2], axis=1)
            lengths = lengths[~np.isnan(lengths)]
            if len(lengths) >= args.min_frames:
                session_medians[bone].append(np.median(lengths))
        logger.info(f'{points_3d_dir}: {clean.sum()} clean frames')

print('# Generated by tools/estimate_bone_lengths.py: [length, tolerance] in mm')
for key, pairs in sections.items():
    print(f'  {key}:')
    for bone in pairs:
        medians = np.array(session_medians[bone])
        if len(medians) == 0:
            print(f"    # '{bone}': no data")
            continue
        low, high = medians.min(), medians.max()
        length = (low + high) / 2
        tolerance = (high - low) / 2 + args.margin * length
        print(f"    '{bone}': [{length:.0f}, {tolerance:.0f}] # session medians {low:.0f}-{high:.0f} (n={len(medians)})")
